#pragma once
#include "vehicle.h"

// ── Physical constants ────────────────────────────────────────────────────────
constexpr double GRAVITY      = 9.81;    // m/s²
constexpr double AIR_DENSITY  = 1.225;   // kg/m³
constexpr double FRONTAL_AREA = 1.5;     // m²

// Lift coefficient per degree of wing angle.
// Gives ~1723 N downforce at v=50 m/s, wing=15°, mass=720 kg (~24 % normal force increase).
constexpr double K_LIFT     = 0.05;

// Extra drag coefficient added per degree of wing angle.
// Creates the high-downforce vs. high-drag tradeoff.
constexpr double K_WING_DRAG = 0.008;

// Precomputed: 0.5 * rho * A * K_LIFT
constexpr double K_DF = 0.5 * AIR_DENSITY * FRONTAL_AREA * K_LIFT;  // ≈ 0.04594

// Engine power (W) by gear preset
constexpr double POWER_SHORT  = 160'000.0;
constexpr double POWER_MEDIUM = 185'000.0;
constexpr double POWER_LONG   = 210'000.0;

// ── Force computations ────────────────────────────────────────────────────────

// Additional downforce generated by wings at speed v
double compute_downforce(double v, const VehicleSetup& setup);

// Total normal force on the car at speed v (weight + downforce)
double compute_normal_force(double v, const VehicleSetup& setup);

// Aerodynamic drag force at speed v (base Cd + wing drag)
double compute_drag_force(double v, const VehicleSetup& setup);

// Maximum tractive engine force at speed v
double compute_engine_force(double v, const VehicleSetup& setup);

// Maximum braking force given current normal force
// brake_bias closest to 0.62 yields best effectiveness
double compute_brake_force(const VehicleSetup& setup, double normal_force);

// ── Derived quantities ────────────────────────────────────────────────────────

// Grip-limited maximum cornering speed for a given radius.
// Solved analytically from the friction-circle constraint including downforce.
double compute_max_corner_speed(double radius, const VehicleSetup& setup);

// Estimated braking distance from v0 → v1 (v0 > v1).
// Uses average-speed approximation for downforce and drag — accurate enough for look-ahead.
double compute_braking_distance(double v0, double v1, const VehicleSetup& setup);
